using ClientSourceGenerator;
using Microsoft.Extensions.DependencyInjection;

namespace TRO.Clients
{
	public static class Services
	{
		public static IServiceCollection AddTroClients(this IServiceCollection services) => services
			.AddAutoGeneratedClients()
			.AddScoped<IRestClient, RestClient>()
			.AddTransient<ILoginClient, LoginClient>();
	}
}